apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - name: docker-demo
        image: manyarai/docker-demo:latest
        ports:
        - containerPort: 9999
