apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
spec:
  selector:
    app: docker-demo
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: LoadBalancer
